Usage Page (Desktop),                   ; Generic desktop controls (01h)
Usage (Gamepad),                        ; Gamepad (05h, application collection)
Collection (Application),
    Collection (Logical),
        Logical Minimum (0),
        Logical Maximum (1),
        Physical Minimum (0),
        Physical Maximum (1),
        Report Size (1),
        Report Count (13),
        Usage Page (Button),            ; Button (09h)
        Usage Minimum (01h),
        Usage Maximum (0Dh),
        Input (Variable),
        Report Count (3),
        Input (Constant),
        Usage Page (Desktop),           ; Generic desktop controls (01h)
        Logical Maximum (7),
        Physical Maximum (315),
        Report Size (4),
        Report Count (1),
        Unit (Degrees),
        Usage (Hat Switch),             ; Hat switch (39h, dynamic value)
        Input (Variable, Null State),
        Unit,
        Report Count (1),
        Input (Constant),
        Logical Maximum (255),
        Physical Maximum (255),
        Usage (X),                      ; X (30h, dynamic value)
        Usage (Y),                      ; Y (31h, dynamic value)
        Usage (Z),                      ; Z (32h, dynamic value)
        Usage (Rz),                     ; Rz (35h, dynamic value)
        Report Size (8),
        Report Count (4),
        Input (Variable),
        Usage Page (FF00h),             ; FF00h, vendor-defined
        Usage (20h),
        Usage (21h),
        Usage (22h),
        Usage (23h),
        Usage (24h),
        Usage (25h),
        Usage (26h),
        Usage (27h),
        Usage (28h),
        Usage (29h),
        Usage (2Ah),
        Usage (2Bh),
        Report Count (12),
        Input (Variable),
        Usage (2621h),
        Report Count (8),
        Feature (Variable),
        Usage (2621h),
        Output (Variable),
        Logical Maximum (1023),
        Physical Maximum (1023),
        Usage (2Ch),
        Usage (2Dh),
        Usage (2Eh),
        Usage (2Fh),
        Report Size (16),
        Report Count (4),
        Input (Variable),
    End Collection,
    Collection (Logical),
        Logical Maximum (255),
        Physical Maximum (255),
        Report Count (7),
        Report Size (8),
        Usage (03h),
        Output (Variable),
    End Collection,
End Collection
